version: "3.8"

services:
  # mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    networks:
      - demo-network
    volumes:
      - mongo-data:/data/db

  # mongo-express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - demo-network
    depends_on:
      - mongodb

  # backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - demo-network
    depends_on:
      - mongodb

  # frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - demo-network
    depends_on:
      - backend

networks:
  demo-network:
    driver: bridge

volumes:
  mongo-data:

# version: "3.8"

# services:
#   # mongodb
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#       - MONGO_INITDB_DATABASE=docker-with-cicd
#     networks:
#       - demo-network
#     volumes:
#       - mongo-data:/data/db

#   # mongo-express
#   mongo-express:
#     image: mongo-express:latest
#     container_name: mongo-express
#     ports:
#       - "8081:8081"
#     environment:
#       - ME_CONFIG_BASICAUTH_USERNAME=admin
#       - ME_CONFIG_BASICAUTH_PASSWORD=password
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#       - ME_CONFIG_MONGODB_SERVER=mongodb
#     networks:
#       - demo-network
#     depends_on:
#       - mongodb

#   # backend
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     ports:
#       - "5000:5000"
#     env_file:
#       - ./backend/.env
#     networks:
#       - demo-network
#     depends_on:
#       - mongodb

#   # frontend
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     env_file:
#       - ./frontend/.env
#     networks:
#       - demo-network
#     depends_on:
#       - backend

# networks:
#   demo-network:
#     driver: bridge

# volumes:
#   mongo-data:
